language: objective-c
osx_image: xcode7
script:
  - xcodebuild -project Peak.xcodeproj -scheme PeakiOS -sdk iphonesimulator test | xcpretty -c
  - xcodebuild -project Peak.xcodeproj -scheme PeakOSX -sdk macosx test | xcpretty -c
